/*
    C8051F005_Init: 
    this module contains all the initialization/configuration routines for     
    this project (device C8051F005). 
*/
#define _C8051F005_INIT_C_ 

/*
    includes 
*/
#include "./SiLABS/c8051F000.h"
#include "on_off.h"
#include "C8051F005_Init.h"

/*
    function prototypes 
*/
void vWatchdog(bit status); 
void vOSC_Init(void); 
void vTimer3_Init(unsigned int counts); 
void vDAC0_Init(void); 

/*
    16-bit SFR defs 
*/
sfr16 TMR3RL    = 0x92;                 // timer 3 reload address (low byte) 
sfr16 TMR3      = 0x94;                 // timer 3 counter address (LB) 
sfr16 DAC0      = 0xD2;                 // DAC0 data word reg. address (LB)

/*
    routines 
*/
/*
    vWatchdog:
    turn watchdog timer ON or OFF.

    parameters: status
        bit status: 
        pass ON(1) or OFF(0) to keep watchdog ON or OFF, respectively. 
    return    : none
*/
void vWatchdog(bit status){
    
    if(status==ON)
        return;                         // watchdog is enabled on power-on
    else{
        WDTCN=0xDE;                     // disable watchdog timer
        WDTCN=0xAD;
    }

}

/*
    vOSC_Init:
    use internal oscillator (OSCICN) at 16MHz (SYSCLK) and turn off external
    oscillator (OSCXCN)

    parameters: none
    return    : none
*/
void vOSC_Init(void){
    
    // XOSCMD2-0=000 (off) and XFCN2-0=000 (default)
    OSCXCN&=~0x70; 
    // MSCLKE=0, CLKSL=0 (internal), IOSCEN=1 (default) and IFCN1-0=11 16MHz
    OSCICN|=0x03;                                    

}

/*
    vTimer3_Init:
    timer 3 uses SYSCLK as timebase, the reload value is assigned -<counts> 
    parameter and timer 3 is loaded initially with the reload value. the 
    interrupts request (IRQ) generated by the TF3 flag is enabled. 

    parameters: counts 
        unsigned int counts: 
        timer 3 overflow rate. 
    return    : none 
*/
void vTimer3_Init(unsigned int counts){ 
    
    TMR3CN|=0x02;                       // T3M=1, timer 3 SYSCLK clock select. 
                                        
    TMR3RL=-counts;                     // timer 3 reload/load of -<counts>  
    TMR3=TMR3RL;                        

    EIE2|=0x01;                         // ET3=1, timer 3 interrupts enabled  
   
}

/*
    vDAC0_Init: 
    enable DAC0 and the data-word is left-justified. DAC0 internal bias and 
    Vref buffer enabled. 
    
    paramters: none 
    return   : none 
*/
void vDAC0_Init(void){

    REF0CN|=0x03;                       // BIASE=1 and REFBE=1  

    DAC0CN|=0x84;                       // DAC0EN=1 and DAC0DF=1xx                     
    
}



